services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - storage
      - database

  storage:
    container_name: storage
    restart: always
    image: redis
    volumes:
      - ./data/storage:/data

  database:
    container_name: database
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./init/database:/docker-entrypoint-initdb.d

  adminer:
    container_name: adminer
    restart: always
    image: adminer
    depends_on:
      - database
    ports:
      - 8080:8080