services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - storage
      - database

  storage:
    container_name: storage
    image: redis:latest
    restart: always

  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080